---
title: "'Exit Try' só pode aparecer dentro da instrução 'Try'"
ms.date: 07/20/2015
f1_keywords:
- vbc30393
- bc30393
helpviewer_keywords:
- BC30393
ms.assetid: b8651df3-a32f-478c-a6d8-aa0ef584155f
ms.openlocfilehash: 5280b041f1219ab9577e684c0814c13821ed9de0
ms.sourcegitcommit: f8c270376ed905f6a8896ce0fe25b4f4b38ff498
ms.translationtype: MT
ms.contentlocale: pt-BR
ms.lasthandoff: 06/04/2020
ms.locfileid: "84397110"
---
# <a name="exit-try-can-only-appear-inside-a-try-statement"></a>'Exit Try' só pode aparecer dentro da instrução 'Try'
`Exit Try`Só pode aparecer dentro de uma `Try` instrução Block. Você tem uma instrução redundante `Exit Try` ou sua `Exit Try` instrução aparece fora dos limites de seu `Try` bloco correspondente.  
  
 **ID do erro:** BC30393  
  
## <a name="to-correct-this-error"></a>Para corrigir este erro  
  
1. Localize e remova a instrução desnecessária `Exit Try` .  
  
2. Mova a `Exit Try` instrução para o local apropriado dentro do seu código.  
  
## <a name="see-also"></a>Confira também

- [Instrução Try...Catch...Finally](../language-reference/statements/try-catch-finally-statement.md)
