---
title: "'Catch' não pode aparecer fora de uma instrução 'Try'"
ms.date: 07/20/2015
f1_keywords:
- bc30380
- vbc30380
helpviewer_keywords:
- BC30380
ms.assetid: 73ce950d-881f-4532-8024-40a4930abd32
ms.openlocfilehash: c8e2b8f9ea5bf5165a97c5b38261a79df1e3b894
ms.sourcegitcommit: f8c270376ed905f6a8896ce0fe25b4f4b38ff498
ms.translationtype: MT
ms.contentlocale: pt-BR
ms.lasthandoff: 06/04/2020
ms.locfileid: "84403752"
---
# <a name="catch-cannot-appear-outside-a-try-statement"></a>'Catch' não pode aparecer fora de uma instrução 'Try'
`Catch`deve aparecer dentro de um `Try...Catch...Finally` bloco de instruções. Você tem uma instrução desnecessária `Catch` em seu `Try` bloco ou sua `Catch` instrução aparece fora dos limites de seu `Try` bloco correspondente.  
  
 **ID do erro:** BC30380  
  
## <a name="to-correct-this-error"></a>Para corrigir este erro  
  
1. Exclua a `Catch` instrução se ela for desnecessária ou coloque-a em um `Try...Catch...Finally` bloco de instruções.  
  
## <a name="see-also"></a>Confira também

- [Instrução Try...Catch...Finally](../language-reference/statements/try-catch-finally-statement.md)
